=== tonyruizo/XML-Workshop/orders.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
   New Perspectives on XML
   Tutorial 3
   Case Problem 4

   Map Finds For You schema
   Author:  Tony Ruiz Ormeno
   Date:     6/11/23

   Filename:         orders.xsd
   Supporting Files: orders.xml
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="customers">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="customer" minOccurs="1" maxOccurs="unbounded">

        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  

  <xs:simpleType name="idType">
    <xs:restriction base="xs:ID">
      <xs:pattern value="cust\d{3}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="cidType">
    <xs:restriction base="xs:ID">
      <xs:pattern value="or\d{4}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="titleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Mr."/>
      <xs:enumeration value="Ms."/>
      <xs:enumeration value="Mrs."/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="phoneType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\(\d{3}\) \d{3}-\d{4}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="qtyType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="saleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Y"/>
      <xs:enumeration value="N"/>
    </xs:restriction>
  </xs:simpleType>
  

  <xs:complexType name="nameType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="title" type="titleType" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="itemPriceType">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
        <xs:attribute name="saleItem" type="saleType" default="N"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  

  <xs:element name="customer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="nameType"/>
        <xs:element name="address" type="xs:string"/>
        <xs:element name="phone" type="phoneType"/>
        <xs:element name="email" type="xs:string" minOccurs="0"/>
        <xs:element name="orders">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="order" minOccurs="1" maxOccurs="unbounded">

              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="custID" type="idType" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="order">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="orderDate" type="xs:date"/>
        <xs:element name="items">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item" minOccurs="1" maxOccurs="unbounded">
                
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="orderID" type="cidType" use="required"/>
      <xs:attribute name="orderBy" type="xs:IDREF" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="itemPrice" type="itemPriceType"/>
        <xs:element name="itemQty" type="qtyType"/>
      </xs:sequence>
      <xs:attribute name="itemNumber" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== tonyruizo/XML-Workshop/orders.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!--
   New Perspectives on XML
   Tutorial 3
   Case Problem 4

   Map Finds For You orders
   Author: Tony Ruiz Ormeno
   Date:   6/11/23

   Filename:          orders.xml
   Supporting Files:  orders.xsd 
-->

<customers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="orders.xsd">
   <customer custID="cust201">
      <name title="Mr.">John Michael</name>
      <address>
         <![CDATA[
         41 West Plankton Avenue
         Orlando, FL  32820
         ]]>
      </address>
      <phone>(407) 555-3476</phone>
      <email>jk@example.net</email>
      <orders>
         <order orderID="or1089" orderBy="cust201">
            <orderDate>2016-08-11</orderDate>
            <items>
	       <item itemNumber="WM100PL">
               	  <itemPrice saleItem="N">39.95</itemPrice>
               	  <itemQty>1</itemQty>
               </item> 
	       <item itemNumber="WM101P">
               	  <itemPrice saleItem="Y">19.90</itemPrice>
               	  <itemQty>2</itemQty>
               </item> 
            </items>
         </order>
      </orders>
   </customer>
   	
   <customer custID="cust202">
      <name title="Mr.">Dean Abernath</name>
      <address>
         <![CDATA[
         200 Bear Avenue
         Front Royal, VA 22630
         ]]>
      </address>
      <phone>(540) 555-1788</phone>
      <email>dabernath@example.net</email>
      <orders>
         <order orderID="or1021" orderBy="cust202">
            <orderDate>2017-08-01</orderDate>
            <items>
               <item itemNumber="WM100PL">
               	  <itemPrice>29.95</itemPrice>
               	  <itemQty>1</itemQty>
               </item>
               <item itemNumber="WM105L">
               	  <itemPrice>19.95</itemPrice>
               	  <itemQty>1</itemQty>
               </item> 
            </items>
         </order>
         <order orderID="or1122" orderBy="cust202">
            <orderDate>2017-10-01</orderDate>
            <items>
               <item itemNumber="H115E">
               	  <itemPrice saleItem="Y">24.90</itemPrice>
               	  <itemQty>2</itemQty>
               </item>
               <item itemNumber="H115F">
               	  <itemPrice saleItem="N">14.95</itemPrice>
               	  <itemQty>1</itemQty>
               </item> 
            </items>
         </order>
      </orders>
   </customer>

   <customer custID="cust203">
      <name>Riverfront High School</name>
      <address>
         <![CDATA[
         1950 West Magnolia Drive
         River Falls, WI 54022
         ]]>
      </address>
      <phone>(715) 555-4022</phone>
      <orders>
         <order orderID="or1120" orderBy="cust203">
            <orderDate>2017-09-15</orderDate>
            <items>
               <item itemNumber="WM140P">
                  <itemPrice>78.90</itemPrice>
               	  <itemQty>2</itemQty>
               </item> 
            </items>
         </order>
      </orders>
   </customer>
</customers>
